{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
{% set url = data.get('url') %}
{% set summary = data.get('summary') %}
{% set description = data.get('long_description') %}

package:
  name: fs-ossfs
  version: {{ version }}


source:
  - path: ../


build:
  include_recipe: True
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "  

requirements:
  build:
    - python
    - setuptools

  run:
    - boto3~=1.7
    - awscli~=1.16.144
    - fs~=2.2
    - six~=1.10

test:
  imports:
    - fs_ossfs

about:
  home: {{ url }}
  license: MIT
  license_file: LICENSE
  license_family: MIT

  summary: {{ summary }}
  description: {{ description }}
  doc_url: "http://fs-ossfs.readthedocs.io/en/latest/"
  dev_url: {{ url }}